#!/bin/bash

if [ $# -eq 0 ] ; then
  echo "No argument supplied. Version number is expected as argument."
  exit 1
fi

rm -rf ./gantry/source/<%- applicationName %>
(cd ./gantry/source && git clone <%- application.repositoryUrl %> <%- applicationName %> && cd <%- applicationName %> && git checkout revision-$1)

rsync -av ./gantry/source/<%- applicationName %>/deployment/ ./gantry/run/<%- applicationName %>/ --exclude node_modules --delete
cp ./<%- applicationName %>/.env ./gantry/run/<%- applicationName %>/.env
(cd ./gantry/run/<%- applicationName %> && yarn --production)
(cd ./gantry/run/<%- applicationName %> && node units/urb-base-tools/update-ip 127.0.0.1)

(export NODE_ENV=development && cd ./gantry/run/<%- applicationName %> && node units/urb-base-tools/setup-database && unset NODE_ENV)
