#!/bin/bash

<% for(let applicationName in project.applications) { %> (cd ./gantry/run/<%= applicationName %> && node units/urb-base-server/server) &<%if (application.hasTunnel > 0) { %> (sleep 5 && cd ./gantry/run/<%= applicationName %> && node units/cf-devtunnel/tunnel)<% } %><% } %>& fg
