#!/bin/bash

<% for(let applicationName in project.applications) { %> (cd ./gantry/run/<%= applicationName %> && node units/urb-base-server/server) &<% if (project.applications[ applicationName ].hasTunnel > 0) { %> (sleep 7 && cd ./gantry/run/<%= applicationName %> && node units/cf-devtunnel/tunnel) &<% } %><% } %>& fg
