#!/bin/bash

if [ $# -eq 0 ] ; then
  echo "No argument supplied. Version number is expected as argument."
  exit 1
fi

rm -rf ./sandbox/source/<%- applicationName %>
(cd ./sandbox/source && git clone <%- application.repositoryUrl %> <%- applicationName %> && cd <%- applicationName %> && git checkout revision-$1)

rsync -av ./sandbox/source/<%- applicationName %>/deployment/ ./sandbox/run/<%- applicationName %>/ --exclude node_modules --delete
rsync -av ./app-settings/<%- applicationName %>/ ./sandbox/run/<%- applicationName %>/
(cd ./sandbox/run/<%- applicationName %> && yarn --production && yarn add localtunnel && yarn add http-proxy)
(cd ./sandbox/run/<%- applicationName %> && node units/rb-base-tools/updateIP 127.0.0.1)

<%if (application.isArtifact > 0) { %>
rsync -av ./sandbox/source/<%- applicationName %>/ ./sandbox/run/<%- applicationName %>-source/ --exclude node_modules --exclude .git --exclude build --delete
rsync -av ./app-settings/<%- applicationName %>/ ./sandbox/run/<%- applicationName %>-source/
(cd ./sandbox/run/<%- applicationName %>-source && yarn)
<% } %>

(export NODE_ENV=development && cd ./sandbox/run/<%- applicationName %> && node units/rb-appbase-server/setupDatabase && unset NODE_ENV)
