#!/bin/bash

if [ $# -eq 0 ] ; then
  echo "No argument supplied. Version number is expected as argument."
  exit 1
fi

rm -rf ./gantry/deployment/<%- application.applicationName %>
(cd ./gantry/deployment && git clone <%- application.repositoryUrl %> <%- application.applicationName %> && cd <%- application.applicationName %> && git checkout revision-$1)

rsync -av ./gantry/deployment/<%- application.applicationName %>/deployment/ ./gantry/<%- application.applicationName %>/ --exclude node_modules --delete
cp ./<%- application.applicationName %>/.env ./gantry/<%- application.applicationName %>/.env
(cd ./gantry/<%- application.applicationName %> && yarn --production)
(cd ./gantry/<%- application.applicationName %> && node units/urb-base-tools/update-ip 127.0.0.1)

(export NODE_ENV=development && cd ./gantry/<%- application.applicationName %> && node units/urb-base-tools/setup-database && unset NODE_ENV)
