---
- name: (elassandra) Download and unpack
  unarchive:
    src: https://github.com/strapdata/elassandra/releases/download/v2.4.5.4/elassandra-2.4.5.4.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/elassandra-2.4.5.4
    remote_src: True

- name: (elassandra) Upload configuration file
  template:
    src: cassandra-env.sh
    dest: /usr/local/bin/elassandra-2.4.5.4/conf/cassandra-env.sh

- name: (elassandra) Upload cassandra.yaml
  template:
    src: cassandra.yaml
    dest: /usr/local/bin/elassandra-2.4.5.4/conf/cassandra.yaml
    owner: root
    mode: "u+rwx,g+xr,o+xr"

- name: (elassandra) Change owner to ubuntu
  shell: |
    chown -R ubuntu:ubuntu /usr/local/bin/elassandra-2.4.5.4/

- name: (elassandra) Create data dirtectory on storage volume
  file:
    path: /mnt/blockstorage/elassandra/data
    state: directory
    owner: ubuntu
    force: yes

- name: (elassandra) Upload service file
  copy:
    src: cassandra.service
    dest: /etc/systemd/system/cassandra.service
    owner: root
    mode: "u+rwx,g+xr,o+xr"

- name: (elassandra) Reload services
  shell: |
    systemctl daemon-reload

- name: (elassandra) Enable service
  shell: |
    systemctl disable cassandra && systemctl enable cassandra

- name: (elassandra) Start service
  systemd:
    name: cassandra
    state: started
