---
- name: (rebar-web-instance git-clone) Create directory in tools/deployment
  local_action: file
  become: "{{ running_user }}"
  args:
    path: "{{ rebar_home }}/tools/deployment/{{ rebar_instance }}/"
    state: absent
    force: yes

- name: (rebar-web-instance git-clone) Clone repository into tools/deployment
  local_action: git
  become: "{{ running_user }}"
  args:
    repo: "{{ rebar_instance_git_url }}"
    dest: "{{ rebar_home }}/tools/deployment/{{ rebar_instance }}/"
    version: "{{ rebar_instance_git_release_branch }}"
